### ISSUE TITLE
feat: support changing the hash after the page is loaded

### ISSUE THREAD

**Issue by jkoop** [gracious-tech/fetch#13]
I want to be able to experiment with the hash ([technically called the "fragment"](https://www.rfc-editor.org/rfc/rfc3986#section-3.5)) without having to reload the page.

Pardon my terseness...

**Comment by rileysiemens** [comment]
Perhaps by using the [hash change event](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event)

**Comment by shadow-light** [comment]
Hi @jkoop , if you are creating your own app that embeds the iframe you can interact with it via `postMessage`. [Here's an example](https://github.com/gracious-tech/track/blob/859804b000222af77ee1a52b5eb25fd93a8cc90a/src/services/fetch.ts#L98) of listening to events the iframe emits. You can also send messages to control the iframe without reloading it.

**Comment by shadow-light** [comment]
Available options here: https://fetch.bible/access/app/#to-the-app
